### PR TITLE
Defense fix

### PR DESCRIPTION
**Pull request by schoolie**
worked existing defender code into new workerManager system

### CODE REVIEW

**Comment by schoolie** [comment]
Fixes #22

**Comment by schoolie** [comment]
Also fixes #23, since defense creeps aren't counted in workerCreeps.length anymore

**Comment by schoolie3344** [comment]
Hey, I would like to pull this in, but I am currently fuzzy on exactly what will happen. Some changes have been made that I would like to keep while also adding these in. It would be good to talk tonight and learn a way for me to do this smoothly.

**Comment by schoolie** [comment]
Because it still says "This branch has no conflicts with the base branch," you should be able to just merge it in with no problem. Take a look at the "Files changed" tab above to see everything that this PR will do to master. As long as it still makes sense, go ahead and merge. If not, let me know and we'll figure something out.

**Pull request merged**
