### PR TITLE
Basic auto extension building

### PR DESCRIPTION
**Pull request by schoolie**
I think this provides basic extension building functionality that won't break any existing setups. 

It builds a dense linear array with a road down the middle, starting at a flag placement and angling toward the direction encoded in the flag name.

The script executes whenever the RCL changes, or whenever room.memory.forceExtensions is manually set to true.

Possible flag names are:
eb_NE
eb_NW
eb_SE
eb_SW
(eb == extension base)

It cycles through and creates enough construction sites to max out the possible extensions in the room, then stops.

### CODE REVIEW

**Comment by schoolie** [comment]
Threre are also some updates to .eslintrc.js that make the linter ignore global screeps variables. Just add to the file as I did for any new globals we reference in order to keep the error count down.

**Comment by schoolie** [comment]
Meets basic requirements of #15. I would eventually like to add options for different extension patterns, selectable by the name of the flag you place for the base.

**Comment by schoolie3344** [comment]
Sounds like a good idea. We can also have it encounter new flags to receive new directions so we can zigzag around terrain.

**Comment by schoolie3344** [comment]
Leaving the branch here for the aforementioned modifications

**Comment by schoolie** [comment]
created issues #36 and #37 for above ideas

**Comment by schoolie** [comment]
Go ahead and delete. It's better practice to have smaller focused branches for each feature, rather than long running "dev" branches. So we'll just make a new branch when we're ready to work on the new stuff.

**Pull request merged**
